# scripts/package-linux.cmake
foreach(required_variable PACKAGE_ROOT ARCHIVE_PATH GUI_EXECUTABLE CLI_EXECUTABLE SOURCE_ROOT FONT_DIRECTORY)
    if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
        message(FATAL_ERROR "${required_variable} is required")
    endif()
endforeach()

get_filename_component(package_parent "${PACKAGE_ROOT}" DIRECTORY)
get_filename_component(archive_directory "${ARCHIVE_PATH}" DIRECTORY)
file(REMOVE_RECURSE "${PACKAGE_ROOT}")
file(MAKE_DIRECTORY "${PACKAGE_ROOT}" "${PACKAGE_ROOT}/fonts" "${PACKAGE_ROOT}/resources" "${archive_directory}")
file(COPY_FILE "${GUI_EXECUTABLE}" "${PACKAGE_ROOT}/LogGenerator" ONLY_IF_DIFFERENT)
file(COPY_FILE "${CLI_EXECUTABLE}" "${PACKAGE_ROOT}/LogGeneratorCli" ONLY_IF_DIFFERENT)
file(COPY "${SOURCE_ROOT}/Sample Logs" DESTINATION "${PACKAGE_ROOT}")
file(COPY "${FONT_DIRECTORY}/" DESTINATION "${PACKAGE_ROOT}/fonts")
file(COPY_FILE "${SOURCE_ROOT}/resources/windows/log.ico" "${PACKAGE_ROOT}/resources/log.ico" ONLY_IF_DIFFERENT)
file(COPY_FILE "${SOURCE_ROOT}/packaging/linux/run-loggenerator.sh" "${PACKAGE_ROOT}/run-loggenerator.sh" ONLY_IF_DIFFERENT)
file(COPY_FILE "${SOURCE_ROOT}/packaging/linux/install-shortcuts.sh" "${PACKAGE_ROOT}/install-shortcuts.sh" ONLY_IF_DIFFERENT)
file(COPY_FILE "${SOURCE_ROOT}/README.md" "${PACKAGE_ROOT}/README.md" ONLY_IF_DIFFERENT)
file(COPY_FILE "${SOURCE_ROOT}/BUILD.md" "${PACKAGE_ROOT}/BUILD.md" ONLY_IF_DIFFERENT)
file(CHMOD "${PACKAGE_ROOT}/LogGenerator" "${PACKAGE_ROOT}/LogGeneratorCli" "${PACKAGE_ROOT}/run-loggenerator.sh" "${PACKAGE_ROOT}/install-shortcuts.sh" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
file(REMOVE "${ARCHIVE_PATH}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${ARCHIVE_PATH}" --format=zip LogGenerator WORKING_DIRECTORY "${package_parent}" RESULT_VARIABLE archive_result)
if(NOT archive_result EQUAL 0)
    message(FATAL_ERROR "Linux ZIP package creation failed with exit code ${archive_result}")
endif()
message(STATUS "Linux ZIP package: ${ARCHIVE_PATH}")
